### ISSUE TITLE
Absolute time on readme

### ISSUE THREAD

**Issue by ymnliu** [OHNLP/MedTagger#10]
The first sentence on MedTagger says:

> MedTagger contains a suite of programs that the Mayo Clinic NLP program has developed in the past three years.

The phrase `in the past three years` may shift its meaning as time goes. Should we have an absolute year (e.g. 2016?) to make it clear? @qqndrew @sunyangfu

**Comment by sunyangfu** [comment]
Yes that's a good catch. I have updated to 2013 based on the AMIA paper.
