### ISSUE TITLE
Failed to collect dependencies at org.ohnlp.backbone

### ISSUE THREAD

**Issue by MayeeshaHumaira** [OHNLP/MedTagger#20]
Hello,

I am getting the following error when I am trying to resolve the dependencies of the MedTagger using my GitHub token. It would be helpful if you could suggest a solution to this problem.

Error: "
[ERROR] Failed to execute goal on project medtagger: Could not resolve dependencies for project org.ohnlp.medtagger:medtagger:jar:1.0.46: Failed to collect dependencies at o
rg.ohnlp.backbone:API:jar:1.0.0-SNAPSHOT: Failed to read artifact descriptor for org.ohnlp.backbone:API:jar:1.0.0-SNAPSHOT: Could not transfer artifact org.ohnlp.backbone:AP
I:pom:1.0.0-SNAPSHOT from/to backbone-maven (https://maven.pkg.github.com/OHNLP/Backbone): authentication failed for https://maven.pkg.github.com/OHNLP/Backbone/org/ohnlp/backbone/API/1.0.0-SNAPSHOT/API-1.0.0-SNAPSHOT.pom, status: 401 Unauthorized -> [Help 1]
"

**Comment by qqndrew** [comment]
Please refer to the "For Developers" section of the README and perform steps 3/4.

**Comment by MayeeshaHumaira** [comment]
Thank you I have missed that step previously, however, after setting up the token like the way it is stated in README it is giving a new error. The terror is "File "API-1.0.30.pom" does not exist in maven package "org.ohnlp.backbone.API" under owner "OHNLP""

Another question is whether I should be using snapshot? The MedTagger I downloaded has snapshot. Once again thank you for your earlier reply.

**Comment by qqndrew** [comment]
Err, which version of MedTagger are you using? It seems to be quite out of date -- current backbone version in MedTagger dependencies is v2.0.0:
https://github.com/OHNLP/MedTagger/blob/master/pom.xml#L144

Would recommend just updating to latest version and let me know if you run into the same problem again.

The other possible reason would be if you did not grant the appropriate API key permissions -- make sure it has the read:packages permission

**Comment by MayeeshaHumaira** [comment]
I am now getting the following error "D:\JetBeans\MedTagger\src\main\java\org\ohnlp\medtagger\ae\AhoCorasickLookupAnnotator.java:36:32
java: package org.ohnlp.medtagger.type does not exist"

can you tell me where "type" is? I thought "type" would be created during the build but it cannot be found.

**Comment by qqndrew** [comment]
This is autogenerated upon maven run. Since I see jetbeans in your path, I'm assuming you are using intellij. Just run mvn clean install once and then IntelliJ should detect the type class files appropriately as autogenerated source (see attached image for what that looks like)

![image](https://user-images.githubusercontent.com/1640717/201449413-77a98240-504e-4c57-9bbd-e76ae1b36a5c.png)

**Comment by MayeeshaHumaira** [comment]
Thank you for being so helpful I could resolve that problem and run MedTagger in IntelliJ.
