### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by 11mkapadia** [OHNLP/MedTagger#9]
**Describe the bug**
Would you be able to provide more detailed instructions on how to run medtaggerIE on test data. I was not able to have the java application run after modifying the directories.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Java Version 8

**Additional context**

**Comment by qqndrew** [comment]
@11mkapadia Could you describe in more detail why you were not able to have the java application run?
Did you run into an error? If so could you append the error message here?

**Comment by 11mkapadia** [comment]
WARN  ResourceUtilManager:129 - Failed to read a resource from used_resources.txt

I am using the same empty folder as the input and output directory and the /pad rules that were provided.

**Comment by sunyangfu** [comment]
@11mkapadia You may need to use the full path directory. We create a demo video to help with the installation: https://vimeo.com/391512276
